### ISSUE TITLE
Не устанавливается

### ISSUE THREAD

**Issue by c1n1k** [bem/bem-express#93]
Сообщение об ошибке:
```
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN prefer global marked@0.3.6 should be installed with -g

> bem-express@2.0.0 postinstall D:\t\bemexp
> npm run make


> bem-express@2.0.0 make D:\t\bemexp
> enb make

Error: Cannot find module 'postcss-url'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\t\bemexp\.enb\make.js:15:13)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.init (D:\t\bemexp\node_modules\enb\lib\make.js:96:17)
    at module.exports (D:\t\bemexp\node_modules\enb\lib\api\make.js:63:25)
    at Command.<anonymous> (D:\t\bemexp\node_modules\enb\lib\cli\make.js:32:13)
    at Command.listener (D:\t\bemexp\node_modules\commander\index.js:301:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (D:\t\bemexp\node_modules\commander\index.js:615:12)
    at Command.parse (D:\t\bemexp\node_modules\commander\index.js:458:21)
    at Object.<anonymous> (D:\t\bemexp\node_modules\enb\lib\cli\cli.js:22:9)
    at Module._compile (module.js:571:32)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "D:\\Utils\\nodejs\\node.exe" "D:\\Utils\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "make"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! bem-express@2.0.0 make: `enb make`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bem-express@2.0.0 make script 'enb make'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bem-express package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     enb make
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bem-express
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bem-express
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\t\bemexp\npm-debug.log

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "D:\\Utils\\nodejs\\node.exe" "D:\\Utils\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! bem-express@2.0.0 postinstall: `npm run make`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bem-express@2.0.0 postinstall script 'npm run make'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bem-express package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run make
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bem-express
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bem-express
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\t\bemexp\npm-debug.log
```

**Comment by tadatuta** [comment]
Спасибо, исправлено в https://github.com/bem/bem-express/commit/ef231af76d35f131992ba4650763a8bef66d8e47
